###
GET http://localhost:3000/api/posts

###
GET http://localhost:3000/api/posts/25

###
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "JS Objects Deep Analysis",
  "description": "JavaScript Object are the solution ...",
  "category": "Front End Development",
  "author_id": 3
}

###
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "AI Intelligence deep dive",
  "description": "In the last few month AI ...",
  "category": "Artificial Intelligence",
  "author_id": 3
}

###
POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "GraphQl the new way",
  "description": "GraphQL is the new way ...",
  "category": "BackEnd Development",
  "author_id": 8
}

###
PUT http://localhost:3000/api/posts/29
Content-Type: application/json

{
  "title": "GraphQl the new way of ",
  "description": "GraphQL has position ..."
}

####
DELETE http://localhost:3000/api/posts/29
