###
GET http://localhost:3000/api/inmuebles

###
GET  http://localhost:3000/api/inmuebles/65288f77ac2b63411a1a137c

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"30",
    "letra":"Anexo-A",
    "extension": 2000,
    "habitaciones":5,
    "alquilado": true,
    "propietario": "Vulmaro Crown",
    "mailPropietario": "crown910@gmail.com"
}
###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"10",
    "letra":"AA",
    "extension": 2000,
    "habitaciones":6,
    "alquilado": true,
    "propietario": "Takuma Yiu",
    "mailPropietario": "takumayiu567@gmail.com"
}


### UPDATE
PUT http://localhost:3000/api/inmuebles/653ea5796afc34135aef5edf
Content-Type: application/json

{
   "piso":"33",
    "letra":"CAT-2",
    "extension": 8,
    "habitaciones":4,
    "alquilado": true,
    "propietario": "Vulmaro Crown SR.",
    "mailPropietario": "crown_910@gmail.com"
}

### DELETE
DELETE http://localhost:3000/api/inmuebles/653ea5796afc34135aef5edf