#####################################################
                   GETS
#####################################################

###
GET http://localhost:3000/api/inmuebles

###
GET  http://localhost:3000/api/inmuebles/653fcbf59727402f1c35127c

#####################################################
                   POSTS
#####################################################

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"30",
    "letra":"Anexo-A",
    "extension": 2000,
    "habitaciones":5,
    "alquilado": true,
    "propietario": "Vulmaro Crown",
    "mailContacto": "crown910@gmail.com"
}
###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"10",
    "letra":"AA",
    "extension": 2000,
    "habitaciones":6,
    "alquilado": true,
    "propietario": "Takuma Yiu",
    "mailContacto": "takumayiu567@gmail.com"
}

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"5",
    "letra":"C",
    "extension": 1000,
    "habitaciones":2,
    "alquilado": false,
    "propietario": "Bon Carson",
    "mailContacto": "carson_78@hotmail.com"
}

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"20",
    "letra":"D",
    "extension": 2000,
    "habitaciones":3,
    "alquilado": true,
    "propietario": "Rachel Green",
    "mailContacto": "rachel_green45@hotmail.com"
}

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"9",
    "letra":"H",
    "extension": 2500,
    "habitaciones":4,
    "alquilado": true,
    "propietario": "Rick Arora",
    "mailContacto": "arora@yahoo.com"
}

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"19",
    "letra":"T",
    "extension": 3500,
    "habitaciones":5,
    "alquilado": true,
    "propietario": "Santiago Cabrera",
    "mailContacto": "santi_cabrera@gmail.com"
}

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"15",
    "letra":"D",
    "extension": 1500,
    "habitaciones":3,
    "alquilado": true,
    "propietario": "Tony Lopez",
    "mailContacto": "lopez45@gmail.com"
}

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"13",
    "letra":"E",
    "extension": 2500,
    "habitaciones":4,
    "alquilado": true,
    "propietario": "Diego Serrano",
    "mailContacto": "mrserrano@gmail.com"
}

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"4",
    "letra":"G",
    "extension": 2500,
    "habitaciones":4,
    "alquilado": false,
    "propietario": "Rogelio Bonilla",
    "mailContacto": "rbonilla@gmail.com"
}

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"16",
    "letra":"J",
    "extension": 3500,
    "habitaciones":6,
    "alquilado": false,
    "propietario": "Tania Floyd",
    "mailContacto": "tfloyd455@gmail.com"
}

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"24",
    "letra":"T",
    "extension": 3500,
    "habitaciones":6,
    "alquilado": true,
    "propietario": "Ericka Palavichini",
    "mailContacto": "erickaPalava_78@gmail.com"
}

#####################################################
                   UPDATES
#####################################################

###
PUT http://localhost:3000/api/inmuebles/6544d50e879252b3f4375e64
Content-Type: application/json

{
    "piso":"24",
    "letra":"T-2",
    "extension": 3500,
    "habitaciones":8,
    "alquilado": true,
    "propietario": "Ericka Palavichini",
    "mailContacto": "erickaPalava_78@gmail.com"
}

#####################################################
                   POST & UPDATE
#####################################################

###
POST http://localhost:3000/api/inmuebles
Content-Type: application/json

{
    "piso":"8",
    "letra":"F",
    "extension": 3500,
    "habitaciones":6,
    "alquilado": true,
    "propietario": "Peter Russell",
    "mailContacto": "p_rusell_890@gmail.com"
}

### UPDATE
PUT http://localhost:3000/api/inmuebles/6544d54f879252b3f4375e68
Content-Type: application/json

{
    "piso":"9",
    "letra":"F",
    "extension": 3500,
    "habitaciones":6,
    "alquilado": true,
    "propietario": "Peter Russell Senior",
    "mailContacto": "p_rusell_890@gmail.com"
}

#####################################################
                   DELETES
#####################################################
### DELETE
DELETE http://localhost:3000/api/inmuebles/6544d54f879252b3f4375e68