###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "rogermooon",
    "email": "rogermoon@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "rogermoon@gmail.com",
    "password": "12345"

}

###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "bryancook",
    "email": "bryancook23@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "bryancook23@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "samuelhoe",
    "email": "samuelhoe3@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "samuelhoe3@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "sandrabullock",
    "email": "sandrabullock@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "sandrabullock@gmail.com",
    "password": "12345"
}